# @package _global_

# This config defines a common setup for experiments.
# Add it to the defaults of any experiment config.

# A random seed is generated for each run if you don't specify one.
# This is good to avoid overfitting your dev runs to specific seeds.
seed: ${generate_random_seed:}
# Cuda deterministic settings.
cuda_deterministic: false
cuda_strong_deterministic: false

# The root data and output directories to be used in experiments.
data_dir: ${hydra:runtime.cwd}/data
outputs_dir: ${hydra:runtime.cwd}/outputs

# Outputs of an experiment are stored in a directory created by Hydra of the form
# outputs/${outputs_subdir}/${hydra.job.name}/${job_subdir}/${now:%Y-%m-%d_%H-%M-%S-%f}
# This has been designed to allow flexibility and can be configured in the sections below.

# Outputs are saved in outputs/${outputs_subdir}/...
# so you can store them in different physical locations if you want
# by symlink-ing outputs_subdir to a different location.
# outputs_subdir can also be useful to separate "dev" and "run" outputs.
outputs_subdir: dev
# Outputs of experiments generated by a script called job_name
# will be saved in outputs/${outputs_subdir}/job_name/${job_subdir}/...
# This can further be useful to tag experiments run from the same script.
job_subdir: dev

hydra:
  run:
    # Finally, this is where the outputs of an individual run will be stored.
    dir: outputs/${outputs_subdir}/${hydra.job.name}/${job_subdir}/runs/${now:%Y-%m-%d--%H-%M-%S-%f}
  job:
    chdir: true
  verbose: false  # Set to true for logging at debug level.

wandb:
  project: template-project-name
  mode: online
  anonymous: allow
  tags:
    - development
  run_id: null
  run_name: null
  # Make outputs/wandb a symlink if you want to save the wandb summaries elsewhere.
  # Same as with outputs_subdir.
  global_dir: ${hydra:runtime.cwd}/outputs
  use_global_dir: false # Otherwise, use the cwd of the experiment.

run_dir: ${hydra:run.dir}
resuming_dir: null

resuming:
  resume: false
  use_commit: false
  wandb_cache_bust: 0 # Limitation of wandb. Cannot create runs with the same ID if deleted previously.
                      # Use this to refresh the id of the run and make it a "new" run.
  exclude_keys: # Can be a deep key e.g. model.optimizer.lr
    - run_dir
    - data_dir      # To be able to resume by another user.
    - outputs_dir   # To be able to resume by another user.
    - resuming_dir  # To be able to force resume from anywhere.
    - wandb         # To be able to move a run and resume it.
    - resuming.exclude_keys # To be able to add keys on the fly and force resume.
