runai submit \
  --name example-remote-development \
  --interactive \
  --image ic-registry.epfl.ch/mlo/my-project/moalla:latest \
  --pvc runai-mlo-moalla-mlodata1:/mlodata1 \
  --environment EPFL_RUNAI=1 \
  --environment CODE_DIR_IN_PVC=/mlodata1/moalla/my-project/code \
  --environment DATA_DIR_IN_PVC=/mlodata1/moalla/my-project/data \
  --environment OUTPUTS_DIR_IN_PVC=/mlodata1/moalla/my-project/outputs \
  --environment EPFL_RUNAI_INTERACTIVE=1 \
  --environment PYCHARM_IDE_LOCATION=/mlodata1/moalla/remote-development/pycharm \
  -- sleep infinity
