services:
  image-root:
    extends:
      file: compose-base.yaml
      service: build-args
    image: ${IMAGE_NAME}:${IMAGE_PLATFORM}-root-latest
    build:
      platforms:
        - "linux/amd64"
      context: .
      dockerfile: Dockerfile
      target: runtime-generic
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        PACKAGE_NAME: ${PACKAGE_NAME}

  image-user:
    extends:
      service: image-root
    image: ${IMAGE_NAME}:${IMAGE_PLATFORM}-${USR}-latest
    build:
      dockerfile: Dockerfile-user
      target: runtime-user
      args:
        GENERIC_IMAGE: ${IMAGE_NAME}
        IMAGE_PLATFORM: ${IMAGE_PLATFORM}
        GRPID: ${GRPID}
        USRID: ${USRID}
        GRP: ${GRP}
        USR: ${USR}
        PASSWD: ${PASSWD}

  run-local-cpu: # Service to run the image locally with CPU only.
    extends:
      service: image-user
    tty: true
    stdin_open: true
    volumes:
      - ../..:${PROJECT_ROOT_AT}
      # Here you can mount other volumes and symlink directories in data and outputs to them.
    working_dir: ${PROJECT_ROOT_AT}
    environment:
      PROJECT_ROOT_AT: ${PROJECT_ROOT_AT}
      WANDB_API_KEY: ${WANDB_API_KEY}
      PROJECT_NAME: ${PROJECT_NAME}
      PACKAGE_NAME: ${PACKAGE_NAME}
    ipc: host                 # Edit as needed (NGC default recommendations, see /opt/nvidia/entrypoint.d/70-shm-check.sh).
    ulimits:                  # Edit as needed (NGC default recommendations, see /opt/nvidia/entrypoint.d/70-shm-check.sh).
      memlock: -1
      stack: 67108864
    network_mode: host            # Edit as needed. Default to avoid extra complecity from networking.

  dev-local-cpu: # Service to develop locally with CPU only.
    extends:
      service: run-local-cpu
    volumes:
      # To persist IDE settings and cache.
      - ${HOME}/.template-gitconfig:/home/${USR}/.gitconfig
      - ${HOME}/.template-dev-vscode-server:/home/${USR}/.dev-vscode-server
      - ${HOME}/.template-dev-cursor-server:/home/${USR}/.dev-cursor-server
      - ${HOME}/.template-dev-jetbrains-server:/home/${USR}/.jetbrains-server
    environment:
      PYCHARM_IDE_AT: ${PYCHARM_IDE_AT}
      JETBRAINS_SERVER_AT: /home/${USR}/.jetbrains-server
      VSCODE_SERVER_AT: /home/${USR}/.dev-vscode-server
      CURSOR_SERVER_AT: /home/${USR}/.dev-cursor-server

  run-local-cuda: # Service to run the image locally with NVIDIA GPU.
    extends:
      service: run-local-cpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  dev-local-cuda: # Service to develop locally with NVIDIA GPU.
    extends:
      service: dev-local-cpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
